
name: TodoListApps
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.example
packages:
  netfox:
    url: https://github.com/kasketis/netfox.git
    from: 1.21.0
targets:
  TodoListApps:
    type: application
    platform: iOS
    sources: [TodoListApps]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.TodoListApps
      INFOPLIST_FILE: TodoListApps/Info.plist
    dependencies:
        - package: netfox
  TodoListAppsTests:
    type: bundle.unit-test
    platform: iOS
    sources: [TodoListAppsTests]
    dependencies:
      - target: TodoListApps
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TodoListApps.app/TodoListApps"
        BUNDLE_LOADER: "$(TEST_HOST)"
schemes:
  TodoListApps:
    build:
      targets:
        TodoListApps: all
        TodoListAppsTests: all
    test:
        targets:
        - name: TodoListAppsTests
        gatherCoverageData: true
